//go:build hdr_thumbs

package hdrthumb

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// Available reports whether an HDR thumbnail generation backend is available.
func Available() bool {
	return helperPath() != ""
}

// Create generates an HDR thumbnail using the enabled Ultra HDR/JPEG_R backend.
func Create(input []byte, opts Options) (Result, error) {
	return CreateContext(context.Background(), input, opts)
}

// CreateContext generates an HDR thumbnail and terminates the native helper on cancellation.
func CreateContext(ctx context.Context, input []byte, opts Options) (Result, error) {
	detected, err := DetectBytes(input, opts.OriginalContentType)
	if err != nil {
		return Result{}, err
	}
	if detected.Kind == KindNone {
		return Result{}, NewError(ErrUnsupportedHDRKind, KindNone, opts.OriginalName, opts.Size, "source image is not HDR")
	}
	if detected.Kind != KindUltraHDRJPEG {
		return Result{}, NewError(ErrUnsupportedHDRKind, detected.Kind, opts.OriginalName, opts.Size, "only Ultra HDR JPEG_R inputs are supported by the first HDR backend")
	}

	helper := helperPath()
	if helper == "" {
		return Result{}, NewError(ErrHDRBackendUnavailable, detected.Kind, opts.OriginalName, opts.Size, "hdrthumb-helper was not found; run scripts/hdrthumb/build-libultrahdr.sh")
	}

	dir, err := os.MkdirTemp("", "pocketbase-hdrthumb-*")
	if err != nil {
		return Result{}, NewError(errors.Join(ErrHDRGenerationFailed, err), detected.Kind, opts.OriginalName, opts.Size, "failed to create temporary HDR thumbnail directory")
	}
	defer os.RemoveAll(dir)

	inPath := filepath.Join(dir, "input.jpg")
	outPath := filepath.Join(dir, "thumb.jpg")
	if err := os.WriteFile(inPath, input, 0600); err != nil {
		return Result{}, NewError(errors.Join(ErrHDRGenerationFailed, err), detected.Kind, opts.OriginalName, opts.Size, "failed to write HDR thumbnail input")
	}

	cmd := exec.CommandContext(ctx, helper, "resize", inPath, outPath, opts.Size)
	if output, err := cmd.CombinedOutput(); err != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			err = errors.Join(err, ctxErr)
		}
		return Result{}, NewError(errors.Join(ErrHDRGenerationFailed, err), detected.Kind, opts.OriginalName, opts.Size, fmt.Sprintf("libultrahdr helper failed: %s", string(output)))
	}

	out, err := os.ReadFile(outPath)
	if err != nil {
		return Result{}, NewError(errors.Join(ErrHDRGenerationFailed, err), detected.Kind, opts.OriginalName, opts.Size, "failed to read HDR thumbnail output")
	}
	if len(out) == 0 {
		return Result{}, NewError(ErrHDRGenerationFailed, detected.Kind, opts.OriginalName, opts.Size, "libultrahdr helper produced an empty thumbnail")
	}

	evidence := append([]string{}, detected.Evidence...)
	evidence = append(evidence, "generated by hdrthumb-helper linked with Google libultrahdr")
	return Result{ContentType: "image/jpeg", Bytes: out, Evidence: evidence}, nil
}

// ProbeContext requires pinned libultrahdr to parse and fully decode the JPEG_R.
func ProbeContext(ctx context.Context, input []byte) (ProbeResult, error) {
	helper := helperPath()
	if helper == "" {
		return ProbeResult{}, ErrHDRBackendUnavailable
	}
	dir, err := os.MkdirTemp("", "pocketbase-hdrprobe-*")
	if err != nil {
		return ProbeResult{}, err
	}
	defer os.RemoveAll(dir)
	path := filepath.Join(dir, "image.jpg")
	if err := os.WriteFile(path, input, 0600); err != nil {
		return ProbeResult{}, err
	}
	output, err := exec.CommandContext(ctx, helper, "probe", path).CombinedOutput()
	if err != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			err = errors.Join(err, ctxErr)
		}
		return ProbeResult{}, fmt.Errorf("libultrahdr full probe failed: %w: %s", err, string(output))
	}
	var probe ProbeResult
	if err := json.Unmarshal(output, &probe); err != nil {
		return ProbeResult{}, fmt.Errorf("invalid libultrahdr probe output: %w", err)
	}
	if !probe.Metadata || probe.Width <= 0 || probe.Height <= 0 ||
		probe.DecodedWidth != probe.Width || probe.DecodedHeight != probe.Height ||
		probe.GainmapWidth <= 0 || probe.GainmapHeight <= 0 {
		return ProbeResult{}, fmt.Errorf("incomplete libultrahdr probe: %+v", probe)
	}
	return probe, nil
}

// Probe requires pinned libultrahdr to parse and fully decode the JPEG_R.
func Probe(input []byte) (ProbeResult, error) {
	return ProbeContext(context.Background(), input)
}

func helperPath() string {
	if configured := os.Getenv("HDRTHUMB_HELPER"); configured != "" {
		if st, err := os.Stat(configured); err == nil && !st.IsDir() {
			return configured
		}
		return ""
	}
	if path, err := exec.LookPath("hdrthumb-helper"); err == nil {
		return path
	}
	wd, err := os.Getwd()
	if err != nil {
		return ""
	}
	for {
		candidate := filepath.Join(wd, ".deps", "hdrthumb", "bin", "hdrthumb-helper")
		if st, err := os.Stat(candidate); err == nil && !st.IsDir() {
			return candidate
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			break
		}
		wd = parent
	}
	return ""
}
